const char CAPCOM_0_ABILITY [] = {"NO ABILITY$"};
const char CAPCOM_1_ABILITY [] = {"SSHINKU HADOUKEN$"};
const char CAPCOM_2_ABILITY [] = {"CRAGE WAVE$"};
const char CAPCOM_3_ABILITY [] = {"TSB KICK$"};
const char CAPCOM_4_ABILITY [] = {"CS KICK$"};
const char CAPCOM_7_ABILITY [] = {"TENLIGHTENMENT$"};
const char CAPCOM_11_ABILITY [] = {"TTRUE POWER$"};
const char CAPCOM_12_ABILITY [] = {"TEVIL CHARISMA$"};
const char CAPCOM_17_ABILITY [] = {"TSPY$"};
const char CAPCOM_18_ABILITY [] = {"TSHUN GOKU SATSU$"};
const char CAPCOM_19_ABILITY [] = {"SHADOUKEN$"};
const char CAPCOM_20_ABILITY [] = {"TSORRY$"};
const char CAPCOM_21_ABILITY [] = {"CHAYA GAKE$"};
const char CAPCOM_22_ABILITY [] = {"TTAROT CARD$"};
const char CAPCOM_27_ABILITY [] = {"TWHAT GIVES$"};
const char CAPCOM_28_ABILITY [] = {"TSAKURA FIGHT$"};
const char CAPCOM_29_ABILITY [] = {"TCHANGING SCHOOL$"};
const char CAPCOM_31_ABILITY [] = {"CHON SHOU$"};
const char CAPCOM_35_ABILITY [] = {"CS HEAD BUTT$"};
const char CAPCOM_38_ABILITY [] = {"CSORE LOSER$"};
const char CAPCOM_39_ABILITY [] = {"CTENGU STONE$"};
const char CAPCOM_40_ABILITY [] = {"SHEALING$"};
const char CAPCOM_43_ABILITY [] = {"CYELL$"};
const char CAPCOM_45_ABILITY [] = {"CXCOPY$"};
const char CAPCOM_46_ABILITY [] = {"CREVENGE$"};
const char CAPCOM_49_ABILITY [] = {"TEVIL ENERGY$"};
const char CAPCOM_50_ABILITY [] = {"SMIDNIGHT BLISS$"};
const char CAPCOM_51_ABILITY [] = {"CLIFE SUCKER$"};
const char CAPCOM_52_ABILITY [] = {"SGOODNIGHT KISS$"};
const char CAPCOM_58_ABILITY [] = {"TREGRETFUL LOP$"};
const char CAPCOM_59_ABILITY [] = {"TJ O T P$"};
const char CAPCOM_62_ABILITY [] = {"CCOSMO POWER$"};
const char CAPCOM_64_ABILITY [] = {"SCHANGE IMMORTAL$"};
const char CAPCOM_65_ABILITY [] = {"CP D C$"};
const char CAPCOM_66_ABILITY [] = {"SAPPLE FOR YOU$"};
const char CAPCOM_67_ABILITY [] = {"TPLUS B$"};
const char CAPCOM_68_ABILITY [] = {"TBECOMING ONE$"};
const char CAPCOM_69_ABILITY [] = {"TASHURA$"};
const char CAPCOM_72_ABILITY [] = {"TBACK OFF$"};
const char CAPCOM_73_ABILITY [] = {"SSAOTOME DYNAMITE$"};
const char CAPCOM_74_ABILITY [] = {"TENERGY COST$"};
const char CAPCOM_81_ABILITY [] = {"CBOILING BLOOD$"};
const char CAPCOM_82_ABILITY [] = {"CCOOL$"};
const char CAPCOM_83_ABILITY [] = {"TGO FOR IT$"};
const char CAPCOM_86_ABILITY [] = {"TFINISH IT$"};
const char CAPCOM_87_ABILITY [] = {"TMASSAGE$"};
const char CAPCOM_89_ABILITY [] = {"SPOWER STONE$"};
const char CAPCOM_90_ABILITY [] = {"COHKA GAKURE$"};
const char CAPCOM_94_ABILITY [] = {"SCYPHER$"};
const char CAPCOM_97_ABILITY [] = {"SSPINNING LARIAT$"};
const char CAPCOM_98_ABILITY [] = {"SWHISTLE$"};
const char CAPCOM_99_ABILITY [] = {"SC CORRIDOR$"};
const char CAPCOM_103_ABILITY [] = {"SCONFINEMENT$"};
const char CAPCOM_106_ABILITY [] = {"SBERETTA$"};
const char CAPCOM_108_ABILITY [] = {"SROLL BUSTER$"};
const char CAPCOM_111_ABILITY [] = {"SPARTS CHANGE$"};
const char CAPCOM_116_ABILITY [] = {"STRANSFORM$"};
const char CAPCOM_117_ABILITY [] = {"CWINGS$"};
const char CAPCOM_119_ABILITY [] = {"TSTAND BY$"};

const char *CAPCOM_ABILITIES [] = 	{
				CAPCOM_0_ABILITY,
				CAPCOM_1_ABILITY,CAPCOM_2_ABILITY,CAPCOM_3_ABILITY,CAPCOM_4_ABILITY,CAPCOM_0_ABILITY,CAPCOM_0_ABILITY,CAPCOM_7_ABILITY,CAPCOM_0_ABILITY,CAPCOM_0_ABILITY,CAPCOM_0_ABILITY,CAPCOM_11_ABILITY,CAPCOM_12_ABILITY,
				CAPCOM_0_ABILITY,CAPCOM_0_ABILITY,CAPCOM_0_ABILITY,CAPCOM_0_ABILITY,CAPCOM_17_ABILITY,CAPCOM_18_ABILITY,CAPCOM_19_ABILITY,CAPCOM_20_ABILITY,CAPCOM_21_ABILITY,CAPCOM_22_ABILITY,CAPCOM_0_ABILITY,CAPCOM_0_ABILITY,
				CAPCOM_0_ABILITY,CAPCOM_0_ABILITY,CAPCOM_27_ABILITY,CAPCOM_28_ABILITY,CAPCOM_29_ABILITY,CAPCOM_0_ABILITY,CAPCOM_31_ABILITY,CAPCOM_0_ABILITY,CAPCOM_0_ABILITY,CAPCOM_0_ABILITY,CAPCOM_35_ABILITY,CAPCOM_0_ABILITY,
				CAPCOM_0_ABILITY,CAPCOM_38_ABILITY,CAPCOM_39_ABILITY,CAPCOM_40_ABILITY,CAPCOM_0_ABILITY,CAPCOM_0_ABILITY,CAPCOM_43_ABILITY,CAPCOM_0_ABILITY,CAPCOM_45_ABILITY,CAPCOM_46_ABILITY,CAPCOM_0_ABILITY,CAPCOM_0_ABILITY,
				CAPCOM_49_ABILITY,CAPCOM_50_ABILITY,CAPCOM_51_ABILITY,CAPCOM_52_ABILITY,CAPCOM_0_ABILITY,CAPCOM_0_ABILITY,CAPCOM_0_ABILITY,CAPCOM_0_ABILITY,CAPCOM_0_ABILITY,CAPCOM_58_ABILITY,CAPCOM_59_ABILITY,CAPCOM_0_ABILITY,
				CAPCOM_0_ABILITY,CAPCOM_62_ABILITY,CAPCOM_0_ABILITY,CAPCOM_64_ABILITY,CAPCOM_65_ABILITY,CAPCOM_66_ABILITY,CAPCOM_67_ABILITY,CAPCOM_68_ABILITY,CAPCOM_69_ABILITY,CAPCOM_0_ABILITY,CAPCOM_0_ABILITY,CAPCOM_72_ABILITY,
				CAPCOM_73_ABILITY,CAPCOM_74_ABILITY,CAPCOM_0_ABILITY,CAPCOM_0_ABILITY,CAPCOM_0_ABILITY,CAPCOM_0_ABILITY,CAPCOM_0_ABILITY,CAPCOM_0_ABILITY,CAPCOM_81_ABILITY,CAPCOM_82_ABILITY,CAPCOM_83_ABILITY,CAPCOM_0_ABILITY,
				CAPCOM_0_ABILITY,CAPCOM_86_ABILITY,CAPCOM_87_ABILITY,CAPCOM_0_ABILITY,CAPCOM_89_ABILITY,CAPCOM_90_ABILITY,CAPCOM_0_ABILITY,CAPCOM_0_ABILITY,CAPCOM_0_ABILITY,CAPCOM_94_ABILITY,CAPCOM_0_ABILITY,CAPCOM_0_ABILITY,
				CAPCOM_97_ABILITY,CAPCOM_98_ABILITY,CAPCOM_99_ABILITY,CAPCOM_0_ABILITY,CAPCOM_0_ABILITY,CAPCOM_0_ABILITY,CAPCOM_103_ABILITY,CAPCOM_0_ABILITY,CAPCOM_0_ABILITY,CAPCOM_106_ABILITY,CAPCOM_0_ABILITY,CAPCOM_108_ABILITY,
				CAPCOM_0_ABILITY,CAPCOM_0_ABILITY,CAPCOM_111_ABILITY,CAPCOM_0_ABILITY,CAPCOM_0_ABILITY,CAPCOM_0_ABILITY,CAPCOM_0_ABILITY,CAPCOM_116_ABILITY,CAPCOM_117_ABILITY,CAPCOM_0_ABILITY,CAPCOM_119_ABILITY,CAPCOM_0_ABILITY,
				};

