const char SNK_0_ABILITY [] = {"NO ABILITY$"};
const char SNK_1_ABILITY [] = {"CTERRY RUSH$"};
const char SNK_2_ABILITY [] = {"TSHADOW SLICER$"};
const char SNK_3_ABILITY [] = {"SHURRICANE UPPER$"};
const char SNK_4_ABILITY [] = {"SMORPH$"};
const char SNK_5_ABILITY [] = {"TSHRIKE DROP$"};
const char SNK_7_ABILITY [] = {"TDUCK DANCE$"};
const char SNK_8_ABILITY [] = {"SARACHNID$"};
const char SNK_11_ABILITY [] = {"TFACE OFF$"};
const char SNK_12_ABILITY [] = {"SFOGEY FISTS$"};
const char SNK_16_ABILITY [] = {"CW RIDER$"};
const char SNK_20_ABILITY [] = {"SSPIRIT SURGE$"};
const char SNK_22_ABILITY [] = {"SBRING IT ON$"};
const char SNK_24_ABILITY [] = {"SM I A$"};
const char SNK_25_ABILITY [] = {"TDEALER$"};
const char SNK_29_ABILITY [] = {"TPROPHECY$"};
const char SNK_30_ABILITY [] = {"SOVERLAP CRUNCH$"};
const char SNK_31_ABILITY [] = {"CIRON SLICE$"};
const char SNK_32_ABILITY [] = {"CDWINDLING LIFE$"};
const char SNK_33_ABILITY [] = {"SDUST CLOUD$"};
const char SNK_34_ABILITY [] = {"THEY PUPPY$"};
const char SNK_35_ABILITY [] = {"TBALM OF NATURE$"};
const char SNK_36_ABILITY [] = {"CSHIKUROOs FANG$"};
const char SNK_37_ABILITY [] = {"SMAMAHAHA CALL$"};
const char SNK_38_ABILITY [] = {"SWIND WHISPER$"};
const char SNK_39_ABILITY [] = {"SKONRIL$"};
const char SNK_42_ABILITY [] = {"TWARRIOR DANCE$"};
const char SNK_43_ABILITY [] = {"SPEEPING KAY$"};
const char SNK_46_ABILITY [] = {"CI KNOW IT$"};
const char SNK_47_ABILITY [] = {"CEXORCISM CARD$"};
const char SNK_48_ABILITY [] = {"SMIDSUMMER RAIN$"};
const char SNK_49_ABILITY [] = {"TSHOUT$"};
const char SNK_52_ABILITY [] = {"TFRIGID SMIRK$"};
const char SNK_53_ABILITY [] = {"SNRG SYPHON$"};
const char SNK_54_ABILITY [] = {"CYUGAs SPELL$"};
const char SNK_55_ABILITY [] = {"TRISING EVIL$"};
const char SNK_57_ABILITY [] = {"TGIVE YOURSELF$"};
const char SNK_59_ABILITY [] = {"CMYSTIC$"};
const char SNK_60_ABILITY [] = {"TOROCHI WAVE$"};
const char SNK_61_ABILITY [] = {"T182 WAYS$"};
const char SNK_62_ABILITY [] = {"STHUNDERGOD FISTS$"};
const char SNK_64_ABILITY [] = {"CS BRINGER$"};
const char SNK_65_ABILITY [] = {"TXCALIBRE$"};
const char SNK_68_ABILITY [] = {"SPSYCHO CHARGE$"};
const char SNK_69_ABILITY [] = {"TMEAT MUFFIN$"};
const char SNK_72_ABILITY [] = {"TENABLER$"};
const char SNK_73_ABILITY [] = {"TEXORCISM$"};
const char SNK_74_ABILITY [] = {"SBURNING SHINGO$"};
const char SNK_76_ABILITY [] = {"CBLOOD CONTRACT$"};
const char SNK_77_ABILITY [] = {"TCOUNTERBLOW$"};
const char SNK_78_ABILITY [] = {"TBE GENTLE TO ME$"};
const char SNK_81_ABILITY [] = {"TSANITY$"};
const char SNK_84_ABILITY [] = {"TKURF$"};
const char SNK_85_ABILITY [] = {"TAWAKENING$"};
const char SNK_86_ABILITY [] = {"TUNSTOPPABLE$"};
const char SNK_89_ABILITY [] = {"CPOWER MATCH$"};
const char SNK_91_ABILITY [] = {"S100 DEMON NIGHT$"};
const char SNK_100_ABILITY [] = {"CSTEEL BULB$"};
const char SNK_101_ABILITY [] = {"SPHOENIX$"};
const char SNK_104_ABILITY [] = {"TCHANGE$"};
const char SNK_105_ABILITY [] = {"SPONTA LEAF$"};
const char SNK_116_ABILITY [] = {"SENEMY CHASER$"};

const char *SNK_ABILITIES [] = 	{
				SNK_0_ABILITY,
				SNK_1_ABILITY,SNK_2_ABILITY,SNK_3_ABILITY,SNK_4_ABILITY,SNK_5_ABILITY,SNK_0_ABILITY,SNK_7_ABILITY,SNK_8_ABILITY,SNK_0_ABILITY,SNK_0_ABILITY,SNK_11_ABILITY,SNK_12_ABILITY,
				SNK_0_ABILITY,SNK_0_ABILITY,SNK_0_ABILITY,SNK_16_ABILITY,SNK_0_ABILITY,SNK_0_ABILITY,SNK_0_ABILITY,SNK_20_ABILITY,SNK_0_ABILITY,SNK_22_ABILITY,SNK_0_ABILITY,SNK_24_ABILITY,
				SNK_25_ABILITY,SNK_0_ABILITY,SNK_0_ABILITY,SNK_0_ABILITY,SNK_29_ABILITY,SNK_30_ABILITY,SNK_31_ABILITY,SNK_32_ABILITY,SNK_33_ABILITY,SNK_34_ABILITY,SNK_35_ABILITY,SNK_36_ABILITY,
				SNK_37_ABILITY,SNK_38_ABILITY,SNK_39_ABILITY,SNK_0_ABILITY,SNK_0_ABILITY,SNK_42_ABILITY,SNK_43_ABILITY,SNK_0_ABILITY,SNK_0_ABILITY,SNK_46_ABILITY,SNK_47_ABILITY,SNK_48_ABILITY,
				SNK_49_ABILITY,SNK_0_ABILITY,SNK_0_ABILITY,SNK_52_ABILITY,SNK_53_ABILITY,SNK_54_ABILITY,SNK_55_ABILITY,SNK_0_ABILITY,SNK_57_ABILITY,SNK_0_ABILITY,SNK_59_ABILITY,SNK_60_ABILITY,
				SNK_61_ABILITY,SNK_62_ABILITY,SNK_0_ABILITY,SNK_64_ABILITY,SNK_65_ABILITY,SNK_0_ABILITY,SNK_0_ABILITY,SNK_68_ABILITY,SNK_69_ABILITY,SNK_0_ABILITY,SNK_0_ABILITY,SNK_72_ABILITY,
				SNK_73_ABILITY,SNK_74_ABILITY,SNK_0_ABILITY,SNK_76_ABILITY,SNK_77_ABILITY,SNK_78_ABILITY,SNK_0_ABILITY,SNK_0_ABILITY,SNK_81_ABILITY,SNK_0_ABILITY,SNK_0_ABILITY,SNK_84_ABILITY,
				SNK_85_ABILITY,SNK_86_ABILITY,SNK_0_ABILITY,SNK_0_ABILITY,SNK_89_ABILITY,SNK_0_ABILITY,SNK_91_ABILITY,SNK_0_ABILITY,SNK_0_ABILITY,SNK_0_ABILITY,SNK_0_ABILITY,SNK_0_ABILITY,
				SNK_0_ABILITY,SNK_0_ABILITY,SNK_0_ABILITY,SNK_100_ABILITY,SNK_101_ABILITY,SNK_0_ABILITY,SNK_0_ABILITY,SNK_104_ABILITY,SNK_105_ABILITY,SNK_0_ABILITY,SNK_0_ABILITY,SNK_0_ABILITY,
				SNK_0_ABILITY,SNK_0_ABILITY,SNK_0_ABILITY,SNK_0_ABILITY,SNK_0_ABILITY,SNK_0_ABILITY,SNK_0_ABILITY,SNK_116_ABILITY,SNK_0_ABILITY,SNK_0_ABILITY,SNK_0_ABILITY,SNK_0_ABILITY,
				};

